StriideInventoryBundle_homepage:
    pattern:  /
    defaults: { _controller: StriideInventoryBundle:Default:index }

StriideInventoryBundle_admin:
    resource: "@StriideInventoryBundle/Resources/config/routing/item.yml"
    prefix:   /admin/item


