parameters:
#    striide_inventory.example.class: Striide\InventoryBundle\Example


services:
  striide_inventory.types:
    class: Striide\InventoryBundle\Service\TypeService
    arguments: [@doctrine]
