parameters:
#    striide_inventory.example.class: Striide\InventoryBundle\Example


services:
#    striide_inventory.example:
#        class: %striide_inventory.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
