<?php

namespace Striide\InventoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    /**
     * get all items by type
     * @param string $type
     */
    public function findByType($type)
    {
        return $this->getEntityManager()->findAllBy(
            array('type' => $type)
        );
    }
}